{% set name = "pyemu" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyemu-{{ version }}.tar.gz
  sha256: 826ed7170cac5bf452f65ca127ae55831b42a9e0771a9954f46410862558d29c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - flopy
    - matplotlib-base

test:
  imports:
    - pyemu
  commands:
    - pip check
    - python -Werror -c "import pyemu"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pypest/pyemu
  summary: pyEMU is a set of python modules for interfacing with PEST and PEST++
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jtwhite79
    - jdhughes-usgs
    - mnfienen
    - mwtoews
