{% set name = "pyemu" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyemu-{{ version }}.tar.gz
  sha256: 70d202ed0f3d2851fc5b75447458ea331efd5194c9fbd03b6baa15c4bdb03ce7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - flopy
    - matplotlib-base

test:
  imports:
    - pyemu
  commands:
    - pip check
    - python -Werror -c "import pyemu"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pypest/pyemu
  summary: pyEMU is a set of python modules for interfacing with PEST and PEST++
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jtwhite79
    - jdhughes-dev
    - mnfienen
    - mwtoews
