{% set name = "pyemu" %}
{% set version = "1.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyemu-{{ version }}.tar.gz
  sha256: 98344a1f06baa8e762332c978ec6efdf3cb8ab12e090efba6ca5bcee41159557

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61
    - pip
  run:
    - python >=3.8
    - numpy
    - pandas

test:
  imports:
    - pyemu
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pypest/pyemu
  summary: pyEMU is a set of python modules for interfacing with PEST and PEST++
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jtwhite79
    - jdhughes-usgs
    - mnfienen
