{% set name = "pyemu" %}
{% set version = "1.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyemu-{{ version }}.tar.gz
  sha256: f8bd5cef12de2d7dd9e36e9670c909bb54e6c34156e1f98aa66c5ffaea54cf3b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61
    - pip
  run:
    - python >=3.8
    - numpy
    - pandas
    - flopy
    - matplotlib-base

test:
  imports:
    - pyemu
  commands:
    - pip check
    - python -Werror -c "import pyemu"
  requires:
    - pip

about:
  home: https://github.com/pypest/pyemu
  summary: pyEMU is a set of python modules for interfacing with PEST and PEST++
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jtwhite79
    - jdhughes-usgs
    - mnfienen
